### ISSUE TITLE
references to wpub

### ISSUE THREAD

**Issue by llemeurfr** [w3c/lpf#2]
We currently have several references to the wpub spec, especially when we introduce the entry page. 

Now that the Publication Manifest goes forward but the Web Publication is "retained", we have to make reference to pub-manifest for `publication.json`. 

I don't see any harm keeping a reference to the wpub note for `index.html`, as LPF will be a note (if we follow the current consensus), as is wpub. 

Any view on this?

**Comment by wareid** [comment]
I switched a good number of the references in audiobooks to PM where appropriate, and still referenced WP when PM didn't have the content. I think it's fine.

**Comment by iherman** [comment]
I would think that, whenever it is possible, it is better to use pub-manifest, even for the Note. The FPWD should be published this coming Tuesday, the references to /TR would work.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-08-26-pwg#section2-2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Wendy Reid: Laurent - meant to reach out, do you have more issues?<br/>
Laurent Le Meur: I have 2 tiny issues for LPF. One is in pull request #1 it was a wording matter speaking about path in archives where the publication manifest is talking about URL strings. I prefer the renaming the notion of path in URL strings to be consistent with publication manifest.<br/>
… I can merge as soon as we agree. I see Ivan and Luc seems to be OK with that.<br/>
Wendy Reid: Does anyone have concerns with that PR?<br/>
Laurent Le Meur: The other issue I haven’t created a PR yet. It’s only that we still make reference to the web pub manifest, and I have to redirect the reference to the publication - so it’s an editorial.<br/>
Wendy Reid: As someone who just did that 2 weeks ago, it’s a bit of a pain, but not too bad.<br/>
Laurent Le Meur: Everything else is ok. If you can read it before we publish it as well, that would be good.<br/>
… If the people in the group can review - I think this is the final state.<br/>
</details>

**Comment by llemeurfr** [comment]
Fixed on 29/11.
